import React, { useState } from 'react';
import dayjs from 'dayjs';
import {
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    Button,
    TextField,
    FormControl,
    InputLabel,
    Select,
    MenuItem,
    Stack,
    Box,
    IconButton,
    Tooltip,
    useMediaQuery,
    useTheme
} from '@mui/material';
import { Camera, Sparkles, UserPlus } from 'lucide-react';
import type { User, Loan, UserAccount } from '../../@types/types';
import { identifyTransaction, type IdentifiedTransaction } from '../../repositories/file';
import UserDialog from './UserDialog';
import { getBankAccountByAccountId, createBankAccount } from '../../repositories/bankAccount';
import { v7 as uuidv7 } from 'uuid';
import { useCreateLoan } from '../../repositories/loan';
import { useAccounts, type Account } from '../../repositories/account';
import { useUsers } from '../../repositories/user';

interface LoanDialogProps {
    onAddLoan: (loan: Loan) => void;
    currentLoansCount: number;
    fixedGuarantorId?: string;
    children?: React.ReactNode;
}

const LoanDialog: React.FC<LoanDialogProps> = ({ onAddLoan, fixedGuarantorId, children }) => {
    const [newLoan, setNewLoan] = useState({
        clientId: '',
        principal: 0,
        interestRate: 10,
        termMonths: 12,
        guarantorId: fixedGuarantorId || '',
        date: dayjs().format('YYYY-MM-DD'),
        sourceAcct: ''
    });
    const theme = useTheme()
    const [open, setOpen] = useState(false)
    const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
    const [imgData, setImgData] = useState<IdentifiedTransaction | null>(null);
    const [found, setFound] = useState(false);
    const [isScanning, setIsScanning] = useState(false);
    const createLoan = useCreateLoan()
    const { data: accounts = [] } = useAccounts();
    const { data: users = [] } = useUsers();
    const assetAccounts = accounts.filter((a: Account) => a.section === 'Assets');
    const handleClose = () => {
        setNewLoan({
            clientId: '',
            principal: 0,
            interestRate: 10,
            termMonths: 12,
            guarantorId: fixedGuarantorId || '',
            date: dayjs().format('YYYY-MM-DD'),
            sourceAcct: ''
        });
        setOpen(false);
    };

    const handleAdd = async () => {
        const loan: Loan = {
            id: uuidv7(),
            alternateId: '', // Generated by backend
            clientId: newLoan.clientId,
            principal: newLoan.principal,
            interestRate: newLoan.interestRate,
            termMonths: newLoan.termMonths,
            date: newLoan.date,
            status: 'Active',
            guarantorId: newLoan.guarantorId || undefined,
            sourceAcct: newLoan.sourceAcct,
            fileId: newLoan.fileId
        };
        if (!found && !!imgData) {
            var userAcct: UserAccount = {
                name: imgData.recipientName,
                accountNumber: imgData.recipientAcct,
                bank: imgData.recipientBank,
                userId: newLoan.clientId
            }
            await createBankAccount(userAcct);
        }
        await createLoan.mutateAsync(loan).then(res => onAddLoan(res));
        handleClose();
        setNewLoan({
            clientId: '',
            principal: 0,
            interestRate: 10,
            termMonths: 12,
            guarantorId: fixedGuarantorId || '',
            date: dayjs().format('YYYY-MM-DD'),
            sourceAcct: '',
            fileId: newLoan.fileId
        });
    };


    const handleAddUser = (user: User) => {
        setNewLoan(prev => ({
            ...prev,
            clientId: user.id
        }));
    };

    const handleImageUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        setIsScanning(true);
        try {
            const data = await identifyTransaction(file);
            if (data) {
                //get user By accountId
                setImgData(data);

                var acct = await getBankAccountByAccountId(data.recipientAcct)
                    .catch(err => {
                        console.error("Error getting bank account:", err);
                        return null;
                    });

                setFound(acct != null)

                var recipient = await getBankAccountByAccountId(data.senderAcct)
                    .catch(err => {
                        console.error("Error getting bank account:", err);
                        return null;
                    });

                setNewLoan(prev => ({
                    ...prev,
                    clientId: acct?.userId || '',
                    principal: data.amount || prev.principal,
                    sourceAcct: recipient?.accountId || prev.sourceAcct,
                    fileId: data.fileId || null,
                    date: data.datetime ? dayjs(data.datetime).format('YYYY-MM-DD') : prev.date
                }));
            }
        } catch (error) {
            console.error("Error identifying transaction:", error);
        } finally {
            setIsScanning(false);
            // Reset input
            event.target.value = '';
        }
    };

    return <>
        {React.cloneElement(children, { onClick: () => setOpen(true) })}
        <Dialog open={open} onClose={handleClose} maxWidth="xs" fullScreen={isMobile} fullWidth>
            <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                Issue New Loan
                <Box>
                    <input
                        type="file"
                        accept="image/*"
                        style={{ display: 'none' }}
                        id="loan-scan-input"
                        onChange={handleImageUpload}
                    />
                    <label htmlFor="loan-scan-input">
                        <Button
                            component="span"
                            variant="outlined"
                            size="small"
                            startIcon={isScanning ? <Sparkles className="animate-pulse" size={16} /> : <Camera size={16} />}
                            disabled={isScanning}
                            sx={{ borderRadius: 2 }}
                        >
                            {isScanning ? 'Scanning...' : 'Scan Receipt'}
                        </Button>
                    </label>
                </Box>
            </DialogTitle>
            <DialogContent>
                <Stack spacing={2} sx={{ mt: 1 }}>
                    <Stack direction="row" spacing={1} alignItems="flex-end">
                        <FormControl fullWidth>
                            <InputLabel>Client</InputLabel>
                            <Select
                                value={newLoan.clientId}
                                label="Client"
                                onChange={(e) => setNewLoan({ ...newLoan, clientId: e.target.value })}
                            >
                                {users.filter(u => u.role === 'Client').map(u => (
                                    <MenuItem key={u.id} value={u.id}>{u.name}</MenuItem>
                                ))}
                            </Select>
                        </FormControl>
                        <UserDialog onAddUser={handleAddUser} imgData={imgData}>
                            <Tooltip title="Add New Client">
                                <IconButton color="primary" sx={{ border: '1px solid', borderColor: 'primary.light', borderRadius: 2 }}>
                                    <UserPlus size={20} />
                                </IconButton>
                            </Tooltip>
                        </UserDialog>
                    </Stack>
                    <TextField
                        label="Date"
                        type="date"
                        fullWidth
                        value={newLoan.date}
                        onChange={(e) => setNewLoan({ ...newLoan, date: e.target.value })}
                        slotProps={{ inputLabel: { shrink: true } }}
                    />
                    <TextField
                        label="Principal Amount"
                        type="number"
                        fullWidth
                        value={newLoan.principal}
                        onChange={(e) => setNewLoan({ ...newLoan, principal: Number(e.target.value) })}
                    />
                    <TextField
                        label="Monthly Interest Rate (%)"
                        type="number"
                        fullWidth
                        value={newLoan.interestRate}
                        onChange={(e) => setNewLoan({ ...newLoan, interestRate: Number(e.target.value) })}
                    />
                    <TextField
                        label="Term (Months)"
                        type="number"
                        fullWidth
                        value={newLoan.termMonths}
                        onChange={(e) => setNewLoan({ ...newLoan, termMonths: Number(e.target.value) })}
                    />
                    <FormControl fullWidth>
                        <InputLabel>Guarantor (Optional)</InputLabel>
                        <Select
                            value={newLoan.guarantorId}
                            label="Guarantor (Optional)"
                            onChange={(e) => setNewLoan({ ...newLoan, guarantorId: e.target.value })}
                            disabled={!!fixedGuarantorId}
                        >
                            <MenuItem value="">None</MenuItem>
                            {users.filter(u =>[ 'Guarantor', "Admin"].indexOf( u.role) > -1).map(u => (
                                <MenuItem key={u.id} value={u.id}>{u.name}</MenuItem>
                            ))}
                        </Select>
                    </FormControl>
                    <FormControl fullWidth>
                        <InputLabel>Source Account (Asset)</InputLabel>
                        <Select
                            value={newLoan.sourceAcct}
                            label="Source Account (Asset)"
                            onChange={(e) => setNewLoan({ ...newLoan, sourceAcct: e.target.value })}
                        >
                            {assetAccounts.map((a: Account) => (
                                <MenuItem key={a.id} value={a.id}>{a.name}</MenuItem>
                            ))}
                        </Select>
                    </FormControl>
                </Stack>
            </DialogContent>
            <DialogActions>
                <Button onClick={handleClose}>Cancel</Button>
                <Button
                    onClick={handleAdd}
                    variant="contained"
                    disabled={!newLoan.clientId || newLoan.principal <= 0 || !newLoan.sourceAcct}
                >
                    Issue Loan
                </Button>
            </DialogActions>
        </Dialog></>
};

export default LoanDialog;
