name: Coop-Loans Deploy to Azure Web Apps

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: Default
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@adolf94'
          
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
        
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: frontend
          
      - name: Build React
        run: npm run build
        working-directory: frontend
  
      - name: Substitute JSON 
        uses: restackio/update-json-file-action@2.1
        with:
          file: frontend/dist/config.json
          fields: |
            {
              "apiUrl": "${{ vars.API }}",
              "authUrl": "${{ vars.AUTH_API }}",
              "clientId": "${{ vars.CLIENT_ID }}",
              "apiClientId": "${{ vars.API_CLIENT_ID }}",
              "redirectUri": "${{ vars.REDIRECT_URI }}",
              "authority": "${{ vars.AUTHORITY }}",
              "scope": "openid profile email api://${{vars.API_CLIENT_ID}}/admin api://${{vars.API_CLIENT_ID}}/guarantor",
              "adminRole": "api://${{vars.API_CLIENT_ID}}/admin",
              "guarantorRole": "api://${{vars.API_CLIENT_ID}}/guarantor"
            }

      - name: Build And Deploy Preparation
        run: |
              cp public/staticwebapp.config.json dist/
              echo window.webConfig= > dist/config.js
              cat dist/config.json >> dist/config.js
        working-directory: frontend

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               return await core.getIDToken()
           result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_POND_0087D2C00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend/dist"
          api_location: ""
          skip_app_build: true
          skip_api_build: true
          output_location: "dist"
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_POND_0087D2C00 }}
          action: "close"
